### ISSUE TITLE
Replace Error with TRPCError

### ISSUE THREAD

**Issue by omershac** [SadnaProject/nMarketTirkedu#166]
Please fix this in your component (that was assigned to you in the previous milestone) and reply to this issue with an emoji.
No need to change errors in _HasRepos.ts, tests, or other errors which are only for the developers.

**Comment by ronzi-2002** [comment]
I see that everyone finished with this one. 
Closing issue

**Comment by Omer-Shahar** [comment]
> I see that everyone finished with this one. Closing issue

What about Bar not man?

**Comment by omershac** [comment]
@BpincuBGU I see you haven't posted a smiley yet. Please close the issue after pushing your relevant PR.
