### ISSUE TITLE
needs implementation  for user create in auth controller

### ISSUE THREAD

**Issue by ilaytzarfati1231** [SadnaProject/nMarketTirkedu#19]
In the user component, I have the user repo responsible for all of the users in the system, hence if you create a new user I need you to call the user controller to the function add-user with an id that you already generate and with his name.
Just to let you know, the function is void, you need to keep the id to have contact with the user controller and such.

**Comment by ronzi-2002** [comment]
Isn't that the register function in AuthController?
Do you need something else?
