### ISSUE TITLE
Questions about cart management

### ISSUE THREAD

**Issue by omershac** [SadnaProject/nMarketTirkedu#240]
The function `addProductToCart` gets the amount to add as input.
However, it looks like `removeProductFromCart` removes the product completely, which is an unexpected behavior.
Maybe it's better that both functions will get an amount—if the amount is undefined, the function will remove it completely as it does now.
What do you think about that?

**Comment by ronzi-2002** [comment]
Not really related to me so I don't surely know but I guess its a good idea to make a "decreaseProductQuantityInCart" function.
tagging ilay
@ilaytzarfati1231
