### ISSUE TITLE
Store founder can't create products

### ISSUE THREAD

**Issue by omershac** [SadnaProject/nMarketTirkedu#293]
Bug in function `canCreateProductInStore`.
In addition, the function `getJobsHierarchyOfStore` returns the following error for the founder:
```
store founder not found for store with id: clhzcgrqk0002uxykipmm6huz not found
 ```

**Comment by ronzi-2002** [comment]
@omershac 
I think they both happened because of the same reason. The creation of products now works. Not sure how can i check the jobsHierarchy. 
If it works please close the issue.
thanke
