### ISSUE TITLE
Add functions that get user ID and store ID, and return whether the user can set the price/quantity

### ISSUE THREAD

**Issue by omershac** [SadnaProject/nMarketTirkedu#41]

**Comment by ronzi-2002** [comment]
get userId and storeID given what data(what is/are the parameter/s of the function)?

**Comment by omershac** [comment]
I think you didn't understand. I meant that the signatures should be:
canUserSetProductPriceInStore(userId, storeId): bool
canUserSetProductQuantityInStore(userId, storeId): bool
If the two permissions are always the same, maybe one function is enough:
canUserEditProductInStore(userId, storeId): bool

**Comment by ronzi-2002** [comment]
Oh okay, I think one function is totally enough in this case.

**Comment by ronzi-2002** [comment]
done
