### ISSUE TITLE
Concurrent Purchase

### ISSUE THREAD

**Issue by barmena** [SadnaProject/nMarketTirkedu#438]
I think there is a bug when 2 users try to purchase the last item concurrently. The relevant concurrency test (in the acceptance tests Parallel.test.ts file) fails and after the test terminates it seems like both users succeeded to perform the purchase according to the DB. (there are 2 purchases of 1 item of the same product, but the quantity is not negative somehow, it is 0)
We'll need to figure it out together since it invloves all our components.

**Comment by ilaytzarfati1231** [comment]
@BpincuBGU  try to lock in your class when approaching to purchase or something like that
