### ISSUE TITLE
Bug: Deleting product causes unexpected errors

### ISSUE THREAD

**Issue by omershac** [SadnaProject/nMarketTirkedu#487]
**לבר לא מן** - הפונקציות
getPurchaseByStore
getMyPurchases
getPurchase
זורקות אם יש קנייה של מוצר שכבר נמחק. חייב שזה כן יחזיר את שאר המוצרים, ועבור המוצר שלא קיים שיחזיר null/undefined במקומות המתאימים בלבד, כי כרגע ה-ui הרוס לגמרי במצב כזה

**לברמן** - הפונקציות
getCart
getCartPrice
זורקות אם יש בעגלה מוצר שכבר נמחק. חייב שזה כן יחזיר את שאר המוצרים, ועבור המוצר שלא קיים שיסיר אותו מהעגלה, כי כרגע ה-ui הרוס לגמרי במצב כזה

**Comment by barmena** [comment]
ברמן טיפל בענייניו
